export const ROUTES = {
    ABOUT: "/",
    LINKEDIN: "https://www.linkedin.com/in/alejandro-hervella/",
    GITHUB: "https://github.com/ahervella",

    GAMES: "/games",
    GAMES_EOE: "/eoe",
    GAMES_EOE_VIDEO_TRAILER: "https://www.youtube.com/embed/HUmo7tddaV0?si=0shOd826HQl6IxH4",
    GAMES_EOE_SITE: "https://www.echoes.games/",
    GAMES_EOE_STEAM: "https://store.steampowered.com/app/2644050/Echoes_of_Elysium/",
    GAMES_EOE_LORIC: "https://www.loricgames.com/",
    GAMES_EOE_ANDREA: "https://www.youtube.com/embed/g-80pn0xNKE?si=Ij6Tb2vbEAIYjw-N",
    GAMES_GOTC: "/gotc",
    GAMES_GOTC_SITE: "https://www.gotconquest.com/",
    GAMES_GOTC_APPSTORE: "https://apps.apple.com/us/app/game-of-thrones-conquest/id1035712810",
    GAMES_WEB: "/proj-web",
    GAMES_PICO8: "/proj-pico8",
    GAMES_PICO8_SITE: "https://www.lexaloffle.com/pico-8.php",
    GAMES_AAA: "/aaa",
    GAMES_AAA_STEAM_STREAM: "https://www.youtube.com/embed/53B2i8J0OZs?si=8SupKA6fWX2qbkgC&amp;start=378",
    GAMES_AAA_STEAM_TRAILER: "https://www.youtube.com/embed/TONVL66Bu94?si=FrzeRIIA2FfYvcoP",
    GAMES_AAA_SLIDES: "https://docs.google.com/presentation/d/1pxCwCrKdtLuIMIO4ooIRUvI0faVqsobP9Pvk9ZJM9PA/edit?usp=sharing",
    GAMES_AAA_STEAM: "https://store.steampowered.com/app/1995780/Aliens_After_Ava/",
    GAMES_AAA_GITHUB: "https://github.com/ahervella/ALIENS_AFTER_AVA_2022",
    GAMES_LUN: "/lun",
    GAMES_LUN_GODOT_DEMO: "https://itch.io/embed-upload/3176855?color=8d0000",
    GAMES_LUN_UNITY_DEMO: "https://www.youtube.com/embed/_JfF-pnd-tE?si=Wn4j_y8xe3Dq6Ynx",
    
    ART: "/art",
    ART_DRAWINGS: "/drawings",
    ART_ANIMATION: "/anim",
    ART_DIGITAL: "digital",

    MUSIC: "/music",
    EOE: "https://www.echoes.games/",
    GOTC: "https://www.gotconquest.com/",
    LUNARNAUT: "https://github.com/ahervella/LUNARNAUT_UNITY_2021",
    PICO8: "https://github.com/ahervella/PROJECT_PICO8",
    WEBPAGE: "https://github.com/ahervella/PROJ_WEB"
};